### ISSUE TITLE
Configure E2E tests to run on production and prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#550]
The issue we face here is that we are likely to see different versions of OSIO UI and backend code in preview and production. We will always want to:
* Execute tests against the newest changes in prod-preview to verify the operation of new features, and, at the same time
* Execute regression tests against code in production to verify that regressions are not introduced

The challenges that we face are how to simultaneously test two, potentially very different UI simultaneously.

**Comment by ppitonak** [comment]
I talked about this topic with @rhopp and we came to the conclusion that it's not just about prod and prod-preview but the application could look differently for different users because of using feature toggles.

Since the number of feature toggle is big, the number of possible paths is huge therefore it's not feasible to have multiple branches in fabric8io/fabric8-test repository.

The best approach seems to be doing in E2E tests the same thing that is done in application code - use Unleash/feature toggles directly and branch test logic according that. There are several unknowns/problems with that.

1. Is Unleash service private or public? 
1. If private, could it be opened for us?
2. How are new feature toggles introduces? 
2. How are they decomissioned? 
2. How often do they change?
3. Is it a problem if test report will suddenly provide different results? I.e. when Che 6 is activated for chosen accounts instead of Che 5?

**Comment by ppitonak** [comment]
@corinnekrych @xcoulon do you know answers to these questions?

**Comment by xcoulon** [comment]
@ppitonak let me answer a few questions: Unleash is a private service running on each platform (preprod + prod) under the `f8toggles` deployment name. The unleash API is not exposed to the outside world, but there's an admin console that can be used to configure the feature toggles. The settings should be the same, with no guarantee about it since there's no sync'ing between the environments.
New feature toggles are manually configured when a feature is being developed and should only be made available for some users on prod/preprod. (i.e., the code is merged on `master` branch). Once a feature is set to `released`, the surrounding `if ...` in the code (UI and maybe backend) should be removed, meaning that the feature toggle can also be removed in `unleash`. 
Frequency of change is unknown, it depends on the roadmap of OSIO.

I'm not sure I understand the last question, @ppitonak, but I hope that the rest above answers your questions.

**Comment by ppitonak** [comment]
More details in #586, some parts already implemented or in progress, some will need more discussions in broader team (will be tracked in new issues). Closing this issue.
