### ISSUE TITLE
Configure new Booster E2E tests to run daily on Centos CI

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#552]
Tasks:

- [ ] Create new test user accounts to support the testing. One account will be needed for each production cluster, plus prod-preview (free-stg) and prod-preview (not on free-stg)
- [ ] Generate Centos CI Jenkins credentials for each account
- [ ] Create cico-jobs job definitions for the Boosters - run each booster at least once daily

As a starting point - while we are waiting to get the new user accounts created and their corresponding credentials - we can try running the suite for one quickstart here:  https://github.com/openshiftio/openshiftio-cico-jobs/pull/571

**Comment by ljelinkova** [comment]
What is the progress here? Do you plan to run the tests? 

The tests have been created several months ago and as far as I know they are not maintained. If you do not plan to run them on Jenkins I'd consider deleting them from the repository since they are becoming outdated to the current code. You can always find them in the Git history.
