### ISSUE TITLE
Smoketest running on Centos CI is showing a 90% failure rate

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#581]
See:
https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-smoketest-cluster-one/

The test is running (mostly) successfully when I run the test locally, but it is almost always failing on Centos CI.

Part of the problem is that Centos CI, when running a test suite, reports a single pass/fail value, regardless of how many test cases in the test suite pass or fail.

**Comment by ppitonak** [comment]
The issue is still not solved. There are multiple things that need to be done

* [x] Lucia's fix https://github.com/ljelinkova/fabric8-test/commit/63abee3211cbd461e4078d19e8dd1a36e541f3a5
* [x] wait for chetest Jenkins job to finish, then the smoketest will pass and situation should stabilize
* [ ] don't start smoketest jobs on commit to master (indirectly launched by master job) - remove [this line](https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L1542)
* [ ] remove Jenkins jobs for chetest and analyticstest
* [ ] add resetting of user account directly to smoketest as a afterAll method

**Comment by ppitonak** [comment]
Che 6 was activated which might influence this issue

**Comment by ppitonak** [comment]
chrome=65.0.3325.181 with chromedriver=2.37.544315 fails when Che window/tab is open. It seems to be only problem when run inside Docker container with xvfb, works fine locally on Fedora. Chrome in headless mode seems to solve this issue.

**Comment by ppitonak** [comment]
At the moment
* all accounts are switched to beta features
* CICO infra is unstable
* test fail because of https://github.com/openshiftio/openshift.io/issues/3461

**Comment by ppitonak** [comment]
Most of the problems were solved. Open new issue for new problems with smoketest.
