### ISSUE TITLE
Change the generated space name

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#669]
I'd like to be able to read the exact time the space was created - so I'd like to change the space name to something like test_20180515_1523_12345. Please suggest other possible names if you'd like. We may also try to challenge OSIO a bit with whitespace :-)

@ppitonak 
@ldimaggi 
@pmacik

**Comment by ldimaggi** [comment]
+1 I agree - that would be a nice addition.
I would not introduce white space as that is a functional test. Let's try to keep things a bit simple if possible.   ;-)

**Comment by ppitonak** [comment]
I'm not against changeing it but I would keep it as short as possible...e.g. does `test_` prefix or `2018` add any information? I wouldn't add a whitespace because this string is used not only inside OSIO but also  for GitHub repo name etc.

**Comment by pmacik** [comment]
@ljelinkova @ppitonak @ldimaggi
I'm fine with a change, but I agree to keep the name short and not to introduce whitespaces. The `test` prefix might be too general so what about using `e2e` instead, so that is clear that it comes from our e2e tests. It is also a bit shorter ;).
Let's keep a prefix there since the tests can be run with a different user accounts (not only the test ones).
So the naming would be in a form of `e2eyyyMMddHHmmssSSS`.
WDYT?

**Comment by ldimaggi** [comment]
+1
* Drop the year
* Separate the values with the "-" char

**Comment by pmacik** [comment]
Created a PR https://github.com/fabric8io/fabric8-test/pull/691.
