### ISSUE TITLE
Look into local_cico_run_e2e_tests.sh

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#813]
This was suggested by @jiekang 

- The script that was run from 'npm run image:start', 'local_cico_run_e2e_tests.sh' seems to try to clean things up before and after but it doesn't successfully do so.
- The docker image is also quite large, over 1 GB for me. I think looking at slimming this down would be nice to have too.

**Comment by ppitonak** [comment]
Regarding cleanup, will it be fixed by https://github.com/fabric8io/fabric8-test/pull/807 or is there anything else?

https://github.com/fabric8io/fabric8-test/pull/806 will print the duration of docker image download on Jenkins, I wouldn't try to optimize image size before we have some data.

Is it an issue for local development? Usually only the top layer is rebuild which is very fast and nothing is downloaded from the Internet. Slimming it down won't hurt but IMHO is not a top priority for this use-case.

**Comment by jiekang** [comment]
I agree slimming the image is not a top priority. Given it's for local developer use, I'd probably give it the lowest priority possible hahah.

For what it's worth, the image is 1.13 GB on my system. It's just a pet peeve I guess.

**Comment by ljelinkova** [comment]
The cleanup has been fixed. As for the image size that is not really an issue for e2e tests so I'll close this.
